# Generated by Django 3.2.16 on 2023-01-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0045_sellerpart_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpart',
            name='seller_part_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
